# Generated by Django 5.1.3 on 2024-11-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_transacao_delete_despesa_delete_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
