# Generated by Django 5.1.3 on 2024-11-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_remove_transacao_titulo_alter_transacao_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
