# Generated by Django 5.1.3 on 2024-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.TextField(),
        ),
    ]
