# Generated by Django 5.1.3 on 2026-07-07 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_alter_transacao_options_transacao_atualizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='status',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='Pago', max_length=10),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], default='Receita', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financas.categoria'),
        ),
    ]
