# Generated by Django 5.1.3 on 2026-07-09 19:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_conta_transacao_conta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='grupo_parcelamento',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='numero_parcela',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='origem',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Recorrente', 'Recorrente'), ('Parcelada', 'Parcelada'), ('Cartão', 'Cartão')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='transacao',
            name='total_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('dia_fechamento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('dia_vencimento', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes', to='financas.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de crédito',
                'verbose_name_plural': 'Cartões de crédito',
                'ordering': ['nome'],
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financas.cartaocredito'),
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada'), ('Paga', 'Paga')], default='Aberta', max_length=10)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='financas.cartaocredito')),
            ],
            options={
                'verbose_name': 'Fatura do cartão',
                'verbose_name_plural': 'Faturas do cartão',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('cartao', 'mes', 'ano')},
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='financas.faturacartao'),
        ),
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta financeira',
                'verbose_name_plural': 'Metas financeiras',
                'ordering': ['data_limite', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=10)),
                ('status_padrao', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='Pendente', max_length=10)),
                ('frequencia', models.CharField(choices=[('Mensal', 'Mensal')], default='Mensal', max_length=20)),
                ('quantidade_meses', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias', to='financas.categoria')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorrencias', to='financas.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação recorrente',
                'verbose_name_plural': 'Transações recorrentes',
                'ordering': ['descricao'],
            },
        ),
        migrations.AddField(
            model_name='transacao',
            name='recorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_geradas', to='financas.transacaorecorrente'),
        ),
    ]
